export * from "./header";
export * from "./footer";
export * from "./talk-about-section";
export * from "./home-designs";
export * from "./company-desc-sec";
export * from "../button-on-dark";
export * from "../button-on-light";
export * from "../design-section";
export * from "../props";